spring.application.name=addressAPI
spring.datasource.url=jdbc:mysql://*********:3306/API_CEP
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=*****
spring.datasource.password=*****